name: Rust

on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.rs"
      - "rust/Cargo.lock"
      - "rust/Cargo.toml"
      - ".github/workflows/rust.yml"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "**.rs"
      - "rust/Cargo.lock"
      - "rust/Cargo.toml"
      - ".github/workflows/rust.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out source repository
      uses: actions/checkout@v3

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose

    - name: Format
      run: cargo fmt --check --verbose

    - name: Lint
      run: cargo clippy -- -Dwarnings

    - name: Audit dependencies for security
      run: cargo audit
